---
# Common tasks for all servers
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Install common packages
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ common_packages }}"

- name: Configure firewall
  include_tasks: firewall.yml
