---
# Firewall configuration
- name: Install firewalld
  package:
    name: firewalld
    state: present
  tags: firewall

- name: Enable and start firewalld
  service:
    name: firewalld
    state: started
    enabled: yes
  tags: firewall

- name: Allow SSH
  firewalld:
    service: ssh
    permanent: yes
    state: enabled
  tags: firewall

- name: Allow web traffic
  firewalld:
    port: "{{ webserver_port }}/tcp"
    permanent: yes
    state: enabled
  when: "'webservers' in group_names"
  tags: firewall

- name: Allow database traffic from webserver
  firewalld:
    rich_rule: "rule family='ipv4' source address='192.168.56.100' port port='{{ db_port }}' protocol='tcp' accept"
    permanent: yes
    state: enabled
  when: "'dbservers' in group_names"
  tags: firewall  

- name: Reload firewalld
  command: firewall-cmd --reload
  tags: firewall