---
galaxy_info:
  author: Your Name
  description: Infrastructure role for web and database servers
  company: Your Company
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - webserver
    - database
    - infrastructure

dependencies: []
